title: BiblioTXT
description: La biblioteca de archivos de texto (.txt) en español
show_downloads: false
google_analytics: UA-128570372-1
bibliotxt: https://github.com/bibliotxt/bibliotxt
twitter: https://twitter.com/bibliotxt
theme: jekyll-theme-cayman
